package com.deying.pojo;

// Generated 2016-6-2 15:03:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * GoodsUsed generated by hbm2java
 */
@Entity
@Table(name = "tbl_goods_used",uniqueConstraints = @UniqueConstraint(columnNames = {
		"GOODS_NAME", "NUMS" }))
public class GoodsUsed implements java.io.Serializable {

	private String goodsUsedId;
	private String goodsId;
	private String goodsName;
	private int nums;
	private String userId;
	private String userName;
	private String status;
	private String companyId;
	private String crtUid;
	private Date crtTime;
	private String updUid;
	private Date updTime;

	public GoodsUsed() {
	}

	public GoodsUsed(String goodsUsedId, String goodsId, String goodsName,
			int nums, String userId, String userName, String status) {
		this.goodsUsedId = goodsUsedId;
		this.goodsId = goodsId;
		this.goodsName = goodsName;
		this.nums = nums;
		this.userId = userId;
		this.userName = userName;
		this.status = status;
	}

	public GoodsUsed(String goodsUsedId, String goodsId, String goodsName,
			int nums, String userId, String userName, String status,
			String companyId, String crtUid, Date crtTime, String updUid,
			Date updTime) {
		this.goodsUsedId = goodsUsedId;
		this.goodsId = goodsId;
		this.goodsName = goodsName;
		this.nums = nums;
		this.userId = userId;
		this.userName = userName;
		this.status = status;
		this.companyId = companyId;
		this.crtUid = crtUid;
		this.crtTime = crtTime;
		this.updUid = updUid;
		this.updTime = updTime;
	}

	@Id
	@Column(name = "GOODS_USED_ID", unique = true, nullable = false, length = 128)
	@GeneratedValue(generator = "goodsUsedGenerator")    
	@GenericGenerator(name = "goodsUsedGenerator", strategy = "uuid") 
	public String getGoodsUsedId() {
		return this.goodsUsedId;
	}

	public void setGoodsUsedId(String goodsUsedId) {
		this.goodsUsedId = goodsUsedId;
	}

	@Column(name = "GOODS_ID", nullable = false, length = 128)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@Column(name = "GOODS_NAME", nullable = false, length = 100)
	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	@Column(name = "NUMS", nullable = false)
	public int getNums() {
		return this.nums;
	}

	public void setNums(int nums) {
		this.nums = nums;
	}

	@Column(name = "USER_ID", nullable = false, length = 128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_NAME", nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "STATUS", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COMPANY_ID", length = 128)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "CRT_UID", length = 128)
	public String getCrtUid() {
		return this.crtUid;
	}

	public void setCrtUid(String crtUid) {
		this.crtUid = crtUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRT_TIME", length = 0)
	public Date getCrtTime() {
		return this.crtTime;
	}

	public void setCrtTime(Date crtTime) {
		this.crtTime = crtTime;
	}

	@Column(name = "UPD_UID", length = 128)
	public String getUpdUid() {
		return this.updUid;
	}

	public void setUpdUid(String updUid) {
		this.updUid = updUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPD_TIME", length = 0)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

}
