package com.deying.core.pojo;
// default package
// Generated 2016-7-24 2:53:14 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TblAttendance generated by hbm2java
 */
@Entity
@Table(name = "tbl_attendance")
public class Attendance implements java.io.Serializable
{
    
    private String attendanceId;
    
    private String userId;
    
    private String companyId;
    
    private String userName;
    
    private String lateTimes;
    
    private String latePoint;
    
    private String leaveEarlyTimes;
    
    private String leaveEarlyPoint;
    
    private String overNormal;
    
    private String overSpecial;
    
    private String allDays;
    
    private String attendanceDays;
    
    private String outDays;
    
    private String leaveDays;
    
    private String absentDays;
    
    private String workTimeNormal;
    
    private String workTimeReal;
    
    private Date startTime;
    
    private Date endTime;
    
    private String crtUid;
    
    private Date crtTime;
    
    private String updUid;
    
    private Date updTime;
    
    public Attendance()
    {
    }
    
    public Attendance(String attendanceId, String companyId)
    {
        this.attendanceId = attendanceId;
        this.companyId = companyId;
    }
    
    public Attendance(String attendanceId, String userId, String companyId, String userName, String lateTimes,
        String latePoint, String leaveEarlyTimes, String leaveEarlyPoint, String overNormal, String overSpecial,
        String allDays, String attendanceDays, String outDays, String leaveDays, String absentDays,Date startTime, Date endTime,
        String workTimeNormal, String workTimeReal, String crtUid, Date crtTime, String updUid, Date updTime)
    {
        this.attendanceId = attendanceId;
        this.userId = userId;
        this.companyId = companyId;
        this.userName = userName;
        this.lateTimes = lateTimes;
        this.latePoint = latePoint;
        this.leaveEarlyTimes = leaveEarlyTimes;
        this.leaveEarlyPoint = leaveEarlyPoint;
        this.overNormal = overNormal;
        this.overSpecial = overSpecial;
        this.allDays = allDays;
        this.attendanceDays = attendanceDays;
        this.outDays = outDays;
        this.leaveDays = leaveDays;
        this.absentDays = absentDays;
        this.workTimeNormal = workTimeNormal;
        this.workTimeReal = workTimeReal;
        this.crtUid = crtUid;
        this.crtTime = crtTime;
        this.updUid = updUid;
        this.updTime = updTime;
        this.startTime = startTime;
        this.endTime = endTime;
    }
    
    @Id
    @GeneratedValue(generator = "loanCollectionGenerator")    
    @GenericGenerator(name = "loanCollectionGenerator", strategy = "uuid") 
    @Column(name = "ATTENDANCE_ID", unique = true, nullable = false, length = 128)
    public String getAttendanceId()
    {
        return this.attendanceId;
    }
    
    public void setAttendanceId(String attendanceId)
    {
        this.attendanceId = attendanceId;
    }
    
    @Column(name = "USER_ID", length = 128)
    public String getUserId()
    {
        return this.userId;
    }
    
    public void setUserId(String userId)
    {
        this.userId = userId;
    }
    
    @Column(name = "COMPANY_ID", nullable = false, length = 128)
    public String getCompanyId()
    {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId)
    {
        this.companyId = companyId;
    }
    
    @Column(name = "USER_NAME", length = 100)
    public String getUserName()
    {
        return this.userName;
    }
    
    public void setUserName(String userName)
    {
        this.userName = userName;
    }
    
    @Column(name = "LATE_TIMES", length = 100)
    public String getLateTimes()
    {
        return this.lateTimes;
    }
    
    public void setLateTimes(String lateTimes)
    {
        this.lateTimes = lateTimes;
    }
    
    @Column(name = "LATE_POINT", length = 128)
    public String getLatePoint()
    {
        return this.latePoint;
    }
    
    public void setLatePoint(String latePoint)
    {
        this.latePoint = latePoint;
    }
    
    @Column(name = "LEAVE_EARLY_TIMES", length = 128)
    public String getLeaveEarlyTimes()
    {
        return this.leaveEarlyTimes;
    }
    
    public void setLeaveEarlyTimes(String leaveEarlyTimes)
    {
        this.leaveEarlyTimes = leaveEarlyTimes;
    }
    
    @Column(name = "LEAVE_EARLY_POINT")
    public String getLeaveEarlyPoint()
    {
        return this.leaveEarlyPoint;
    }
    
    public void setLeaveEarlyPoint(String leaveEarlyPoint)
    {
        this.leaveEarlyPoint = leaveEarlyPoint;
    }
    
    @Column(name = "OVER_NORMAL")
    public String getOverNormal()
    {
        return this.overNormal;
    }
    
    public void setOverNormal(String overNormal)
    {
        this.overNormal = overNormal;
    }
    
    @Column(name = "OVER_SPECIAL")
    public String getOverSpecial()
    {
        return this.overSpecial;
    }
    
    public void setOverSpecial(String overSpecial)
    {
        this.overSpecial = overSpecial;
    }
    
    @Column(name = "ALL_DAYS")
    public String getAllDays()
    {
        return this.allDays;
    }
    
    public void setAllDays(String allDays)
    {
        this.allDays = allDays;
    }
    
    @Column(name = "ATTENDANCE_DAYS", length = 10)
    public String getAttendanceDays()
    {
        return this.attendanceDays;
    }
    
    public void setAttendanceDays(String attendanceDays)
    {
        this.attendanceDays = attendanceDays;
    }
    
    @Column(name = "OUT_DAYS", length = 10)
    public String getOutDays()
    {
        return this.outDays;
    }
    
    public void setOutDays(String outDays)
    {
        this.outDays = outDays;
    }
    
    @Column(name = "LEAVE_DAYS", length = 10)
    public String getLeaveDays()
    {
        return this.leaveDays;
    }
    
    public void setLeaveDays(String leaveDays)
    {
        this.leaveDays = leaveDays;
    }
    
    @Column(name = "ABSENT_DAYS", length = 10)
    public String getAbsentDays()
    {
        return this.absentDays;
    }
    
    public void setAbsentDays(String absentDays)
    {
        this.absentDays = absentDays;
    }
    
    @Column(name = "WORK_TIME_NORMAL", length = 10)
    public String getWorkTimeNormal()
    {
        return this.workTimeNormal;
    }
    
    public void setWorkTimeNormal(String workTimeNormal)
    {
        this.workTimeNormal = workTimeNormal;
    }
    
    @Column(name = "WORK_TIME_REAL", length = 10)
    public String getWorkTimeReal()
    {
        return this.workTimeReal;
    }
    
    public void setWorkTimeReal(String workTimeReal)
    {
        this.workTimeReal = workTimeReal;
    }
    
    @Column(name = "CRT_UID", length = 128)
    public String getCrtUid()
    {
        return this.crtUid;
    }
    
    public void setCrtUid(String crtUid)
    {
        this.crtUid = crtUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CRT_TIME", length = 19)
    public Date getCrtTime()
    {
        return this.crtTime;
    }
    
    public void setCrtTime(Date crtTime)
    {
        this.crtTime = crtTime;
    }
    
    @Column(name = "UPD_UID", length = 128)
    public String getUpdUid()
    {
        return this.updUid;
    }
    
    public void setUpdUid(String updUid)
    {
        this.updUid = updUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPD_TIME", length = 19)
    public Date getUpdTime()
    {
        return this.updTime;
    }
    
    public void setUpdTime(Date updTime)
    {
        this.updTime = updTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_TIME", length = 19)
    public Date getStartTime()
    {
        return startTime;
    }

    public void setStartTime(Date startTime)
    {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "END_TIME", length = 19)
    public Date getEndTime()
    {
        return endTime;
    }

    public void setEndTime(Date endTime)
    {
        this.endTime = endTime;
    }
    
}
