package com.deying.core.pojo;

// Generated 2016-6-2 15:03:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * GoodsUsed generated by hbm2java
 */
@Entity
@Table(name = "com_backup")
public class Backup implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "BACKUP_ID", unique = true, nullable = false, length = 128)
	private String backupId;
	@Column(name = "DB_NAME", nullable = false, length = 100)
	private String dbName;
	@Column(name = "PATH", nullable = false, length = 100)
	private String path;
	@Column(name = "BACKUP_NAME", nullable = false, length = 100)
	private String backupName;
	@Column(name = "CRT_UID", length = 128)
	private String crtUid;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRT_TIME", length = 0)
	private Date crtTime;
	@Column(name = "UPD_UID", length = 128)
	private String updUid;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPD_TIME", length = 0)
	private Date updTime;
	public String getBackupId() {
		return backupId;
	}
	public void setBackupId(String backupId) {
		this.backupId = backupId;
	}
	public String getDbName() {
		return dbName;
	}
	public void setDbName(String dbName) {
		this.dbName = dbName;
	}
	public String getPath() {
		return path;
	}
	public void setPath(String path) {
		this.path = path;
	}
	public String getBackupName() {
		return backupName;
	}
	public void setBackupName(String backupName) {
		this.backupName = backupName;
	}
	public String getCrtUid() {
		return crtUid;
	}
	public void setCrtUid(String crtUid) {
		this.crtUid = crtUid;
	}
	public Date getCrtTime() {
		return crtTime;
	}
	public void setCrtTime(Date crtTime) {
		this.crtTime = crtTime;
	}
	public String getUpdUid() {
		return updUid;
	}
	public void setUpdUid(String updUid) {
		this.updUid = updUid;
	}
	public Date getUpdTime() {
		return updTime;
	}
	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

}
