package com.deying.core.pojo;
// default package
// Generated 2016-7-23 19:14:48 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TblBirthdayRemind generated by hbm2java
 */
@Entity
@Table(name = "tbl_birthday_remind")
public class BirthdayRemind implements java.io.Serializable
{
    
    private String birthdayRemindId;
    
    private String name;
    
    private Date birthdayTime;
    
    private String info;
    
    private String status;
    
    private String crtUid;
    
    private Date crtTime;
    
    private String updUid;
    
    private Date updTime;
    
    public BirthdayRemind()
    {
    }
    
    public BirthdayRemind(String birthdayRemindId, String name, Date birthdayTime)
    {
        this.birthdayRemindId = birthdayRemindId;
        this.name = name;
        this.birthdayTime = birthdayTime;
    }
    
    public BirthdayRemind(String birthdayRemindId, String name, Date birthdayTime, String info, String status,
        String crtUid, Date crtTime, String updUid, Date updTime)
    {
        this.birthdayRemindId = birthdayRemindId;
        this.name = name;
        this.birthdayTime = birthdayTime;
        this.info = info;
        this.status = status;
        this.crtUid = crtUid;
        this.crtTime = crtTime;
        this.updUid = updUid;
        this.updTime = updTime;
    }
    
    @Id
    @GeneratedValue(generator = "birthdayRemindGenerator")
    @GenericGenerator(name = "birthdayRemindGenerator", strategy = "uuid")
    @Column(name = "BIRTHDAY_REMIND_ID", unique = true, nullable = false, length = 128)
    public String getBirthdayRemindId()
    {
        return this.birthdayRemindId;
    }
    
    public void setBirthdayRemindId(String birthdayRemindId)
    {
        this.birthdayRemindId = birthdayRemindId;
    }
    
    @Column(name = "NAME", nullable = false, length = 100)
    public String getName()
    {
        return this.name;
    }
    
    public void setName(String name)
    {
        this.name = name;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "BIRTHDAY_TIME", nullable = false, length = 19)
    public Date getBirthdayTime()
    {
        return this.birthdayTime;
    }
    
    public void setBirthdayTime(Date birthdayTime)
    {
        this.birthdayTime = birthdayTime;
    }
    
    @Column(name = "INFO", length = 200)
    public String getInfo()
    {
        return this.info;
    }
    
    public void setInfo(String info)
    {
        this.info = info;
    }
    
    @Column(name = "STATUS", length = 2)
    public String getStatus()
    {
        return this.status;
    }
    
    public void setStatus(String status)
    {
        this.status = status;
    }
    
    @Column(name = "CRT_UID", length = 128)
    public String getCrtUid()
    {
        return this.crtUid;
    }
    
    public void setCrtUid(String crtUid)
    {
        this.crtUid = crtUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CRT_TIME", length = 19)
    public Date getCrtTime()
    {
        return this.crtTime;
    }
    
    public void setCrtTime(Date crtTime)
    {
        this.crtTime = crtTime;
    }
    
    @Column(name = "UPD_UID", length = 128)
    public String getUpdUid()
    {
        return this.updUid;
    }
    
    public void setUpdUid(String updUid)
    {
        this.updUid = updUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPD_TIME", length = 19)
    public Date getUpdTime()
    {
        return this.updTime;
    }
    
    public void setUpdTime(Date updTime)
    {
        this.updTime = updTime;
    }
    
}
