package com.deying.core.pojo;
// default package
// Generated 2016-10-18 21:49:39 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * TblDebt generated by hbm2java
 */
@Entity
@Table(name = "tbl_debt")
public class Debt implements java.io.Serializable
{
    
    private String debtId;
    
    private String financingApplyId;
    
    private String moneyOutBack;
    
    private Date startTime;
    
    private String startMonery;
    
    private String manageMoney;
    
    private String status;
    
    private String companyId;
    
    private String crtUid;
    
    private Date crtTime;
    
    private String updUid;
    
    private Date updTime;
    
    private String customerName;
    
    private String cardId;
    
	private String expireMoney;
	
	private String address;
	
	private String money;
	
	private String noDebtsMoney;
	
	private String contractId;
	
	private Date financingEndTime;
    
    public Debt()
    {
    }
    
    public Debt(String debtId, String financingApplyId)
    {
        this.debtId = debtId;
        this.financingApplyId = financingApplyId;
    }
    
    public Debt(String debtId, String financingApplyId, String moneyOutBack, Date startTime, String startMonery,
        String manageMoney, String companyId, String crtUid, Date crtTime, String updUid, Date updTime, String status, 
        String cardId, String expireMoney, String address, String customerName, String money, String noDebtsMoney,Date financingEndTime,String contractId)
    {
        this.debtId = debtId;
        this.financingApplyId = financingApplyId;
        this.moneyOutBack = moneyOutBack;
        this.startTime = startTime;
        this.startMonery = startMonery;
        this.manageMoney = manageMoney;
        this.companyId = companyId;
        this.crtUid = crtUid;
        this.crtTime = crtTime;
        this.updUid = updUid;
        this.updTime = updTime;
        this.status = status;
        this.expireMoney = expireMoney;
        this.cardId = cardId;
        this.address = address;
        this.customerName = customerName;
        this.money = money;
        this.noDebtsMoney = noDebtsMoney;
        this.financingEndTime = financingEndTime;
        this.contractId = contractId;
    }
    
    @Id
    @Column(name = "DEBT_ID", unique = true, nullable = false, length = 128)
    @GeneratedValue(generator = "financingGenerator")    
    @GenericGenerator(name = "financingGenerator", strategy = "uuid") 
    public String getDebtId()
    {
        return this.debtId;
    }
    
    public void setDebtId(String debtId)
    {
        this.debtId = debtId;
    }
    
    @Column(name = "FINANCING_APPLY_ID", nullable = false, length = 128)
    public String getFinancingApplyId()
    {
        return this.financingApplyId;
    }
    
    public void setFinancingApplyId(String financingApplyId)
    {
        this.financingApplyId = financingApplyId;
    }
    
    @Column(name = "MONEY_OUT_BACK")
    public String getMoneyOutBack()
    {
        return this.moneyOutBack;
    }
    
    public void setMoneyOutBack(String moneyOutBack)
    {
        this.moneyOutBack = moneyOutBack;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_TIME", length = 19)
    public Date getStartTime()
    {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime)
    {
        this.startTime = startTime;
    }
    
    @Column(name = "START_MONERY", length = 100)
    public String getStartMonery()
    {
        return this.startMonery;
    }
    
    public void setStartMonery(String startMonery)
    {
        this.startMonery = startMonery;
    }
    
    @Column(name = "MANAGE_MONEY", length = 100)
    public String getManageMoney()
    {
        return this.manageMoney;
    }
    
    public void setManageMoney(String manageMoney)
    {
        this.manageMoney = manageMoney;
    }
    
    @Column(name = "COMPANY_ID", length = 128)
    public String getCompanyId()
    {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId)
    {
        this.companyId = companyId;
    }
    
    @Column(name = "CRT_UID", length = 128)
    public String getCrtUid()
    {
        return this.crtUid;
    }
    
    public void setCrtUid(String crtUid)
    {
        this.crtUid = crtUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CRT_TIME", length = 19)
    public Date getCrtTime()
    {
        return this.crtTime;
    }
    
    public void setCrtTime(Date crtTime)
    {
        this.crtTime = crtTime;
    }
    
    @Column(name = "UPD_UID", length = 128)
    public String getUpdUid()
    {
        return this.updUid;
    }
    
    public void setUpdUid(String updUid)
    {
        this.updUid = updUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPD_TIME", length = 19)
    public Date getUpdTime()
    {
        return this.updTime;
    }
    
    public void setUpdTime(Date updTime)
    {
        this.updTime = updTime;
    }
    
    
    @Column(name = "STATUS", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@Column(name = "CUSTOMER_NAME",  length = 200)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	
	@Column(name = "EXPIRE_MONEY", length = 200)
	public String getExpireMoney() {
		return this.expireMoney;
	}

	public void setExpireMoney(String expireMoney) {
		this.expireMoney = expireMoney;
	}
	
	@Column(name = "CARD_ID", nullable = false, length = 50)
	public String getCardId() {
		return this.cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}
	
	@Column(name = "ADDRESS", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
	@Column(name = "MONEY", length = 200)
	public String getMoney() {
		return this.money;
	}

	public void setMoney(String money) {
		this.money = money;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FINANCING_END_TIME", nullable = false, length = 0)
	public Date getFinancingEndTime() {
		return this.financingEndTime;
	}

	public void setFinancingEndTime(Date financingEndTime) {
		this.financingEndTime = financingEndTime;
	}
	
	@Column(name = "NO_DEBTS_MONEY", length = 100)
	public String getNoDebtsMoney() {
		return this.noDebtsMoney;
	}

	public void setNoDebtsMoney(String noDebtsMoney) {
		this.noDebtsMoney = noDebtsMoney;
	}
	
	@Column(name = "CONTRACT_ID", length = 128)
	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}
}
