package com.deying.core.pojo;

 
// Generated 2016-7-23 23:33:12 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * FinancingRemind generated by hbm2java
 */
@Entity
@Table(name = "_financing_remind")
public class  FinancingRemind implements java.io.Serializable
{
    
    private String financingRemindId;
    
    private String customerId;
    
    private String customerName;
    
    private String telephone;
    
    private Date startTime;
    
    private String bankCardId;
    
    private String depositBank;
    
    private String money;
    
    private String income;
    
    private String type;
    
    private String dayType;
    
    private String info;
    
    private String employeeId;
    
    private String employeeName;
    
    private String companyId;
    
    private String status;
    
    private String crtUid;
    
    private Date crtTime;
    
    private String updUid;
    
    private Date updTime;
    
    public FinancingRemind()
    {
    }
    
    public FinancingRemind(String financingRemindId)
    {
        this.financingRemindId = financingRemindId;
    }
    
    public FinancingRemind(String financingRemindId, String customerId, String customerName, String telephone,String income,
        Date startTime, String bankCardId, String depositBank, String money, String type, String dayType, String info,
        String employeeId, String employeeName, String companyId, String status, String crtUid, Date crtTime,
        String updUid, Date updTime)
    {
        this.financingRemindId = financingRemindId;
        this.customerId = customerId;
        this.customerName = customerName;
        this.telephone = telephone;
        this.startTime = startTime;
        this.bankCardId = bankCardId;
        this.depositBank = depositBank;
        this.money = money;
        this.income = income;
        this.type = type;
        this.dayType = dayType;
        this.info = info;
        this.employeeId = employeeId;
        this.employeeName = employeeName;
        this.companyId = companyId;
        this.status = status;
        this.crtUid = crtUid;
        this.crtTime = crtTime;
        this.updUid = updUid;
        this.updTime = updTime;
    }
    
    @Id
    @GeneratedValue(generator = "financingNnlGenerator")    
    @GenericGenerator(name = "financingNnlGenerator", strategy = "uuid") 
    @Column(name = "FINANCING_REMIND_ID", unique = true, nullable = false, length = 128)
    public String getFinancingRemindId()
    {
        return this.financingRemindId;
    }
    
    public void setFinancingRemindId(String financingRemindId)
    {
        this.financingRemindId = financingRemindId;
    }
    
    @Column(name = "CUSTOMER_ID", length = 128)
    public String getCustomerId()
    {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId)
    {
        this.customerId = customerId;
    }
    
    @Column(name = "CUSTOMER_NAME")
    public String getCustomerName()
    {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName)
    {
        this.customerName = customerName;
    }
    
    @Column(name = "TELEPHONE")
    public String getTelephone()
    {
        return this.telephone;
    }
    
    public void setTelephone(String telephone)
    {
        this.telephone = telephone;
    }
    
    @Column(name = "INCOME")
    public String getIncome()
    {
        return this.income;
    }
    
    public void setIncome(String income)
    {
        this.income = income;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_TIME", length = 19)
    public Date getStartTime()
    {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime)
    {
        this.startTime = startTime;
    }
    
    @Column(name = "BANK_CARD_ID", length = 100)
    public String getBankCardId()
    {
        return this.bankCardId;
    }
    
    public void setBankCardId(String bankCardId)
    {
        this.bankCardId = bankCardId;
    }
    
    @Column(name = "DEPOSIT_BANK")
    public String getDepositBank()
    {
        return this.depositBank;
    }
    
    public void setDepositBank(String depositBank)
    {
        this.depositBank = depositBank;
    }
    
    @Column(name = "MONEY", precision = 10, scale = 0)
    public String getMoney()
    {
        return this.money;
    }
    
    public void setMoney(String money)
    {
        this.money = money;
    }
    
    @Column(name = "TYPE", length = 2)
    public String getType()
    {
        return this.type;
    }
    
    public void setType(String type)
    {
        this.type = type;
    }
    
    @Column(name = "DAY_TYPE", length = 2)
    public String getDayType()
    {
        return this.dayType;
    }
    
    public void setDayType(String dayType)
    {
        this.dayType = dayType;
    }
    
    @Column(name = "INFO", length = 200)
    public String getInfo()
    {
        return this.info;
    }
    
    public void setInfo(String info)
    {
        this.info = info;
    }
    
    @Column(name = "EMPLOYEE_ID", length = 128)
    public String getEmployeeId()
    {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId)
    {
        this.employeeId = employeeId;
    }
    
    @Column(name = "EMPLOYEE_NAME")
    public String getEmployeeName()
    {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName)
    {
        this.employeeName = employeeName;
    }
    
    @Column(name = "COMPANY_ID", length = 128)
    public String getCompanyId()
    {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId)
    {
        this.companyId = companyId;
    }
    
    @Column(name = "STATUS", length = 2)
    public String getStatus()
    {
        return this.status;
    }
    
    public void setStatus(String status)
    {
        this.status = status;
    }
    
    @Column(name = "CRT_UID", length = 128)
    public String getCrtUid()
    {
        return this.crtUid;
    }
    
    public void setCrtUid(String crtUid)
    {
        this.crtUid = crtUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CRT_TIME", length = 19)
    public Date getCrtTime()
    {
        return this.crtTime;
    }
    
    public void setCrtTime(Date crtTime)
    {
        this.crtTime = crtTime;
    }
    
    @Column(name = "UPD_UID", length = 128)
    public String getUpdUid()
    {
        return this.updUid;
    }
    
    public void setUpdUid(String updUid)
    {
        this.updUid = updUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPD_TIME", length = 19)
    public Date getUpdTime()
    {
        return this.updTime;
    }
    
    public void setUpdTime(Date updTime)
    {
        this.updTime = updTime;
    }
    
}
