package com.deying.core.pojo;
// default package
// Generated 2016-7-24 15:23:14 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * TblFinancingStatistic generated by hbm2java
 */
@Entity
@Table(name = "tbl_financing_statistic" )
public class FinancingStatistic implements java.io.Serializable
{
    
    private String statisticId;
    
    private String employeeId;
    
    private String employeeName;
    
    private String customerNums;
    
    private String moneyAll;
    
    private Integer averageMoney;
    
    private String time;
    
    private String year;
    
    private String timeRange;
    
    private String info;
    
    private String companyId;
    
    private String crtUid;
    
    private Date crtTime;
    
    private String updUid;
    
    private Date updTime;
    
    public FinancingStatistic()
    {
    }
    
    public FinancingStatistic(String statisticId)
    {
        this.statisticId = statisticId;
    }
    
    public FinancingStatistic(String statisticId, String employeeId, String employeeName, String customerNums,
        String moneyAll, Integer averageMoney, String time, String year, String timeRange, String info,
        String companyId, String crtUid, Date crtTime, String updUid, Date updTime)
    {
        this.statisticId = statisticId;
        this.employeeId = employeeId;
        this.employeeName = employeeName;
        this.customerNums = customerNums;
        this.moneyAll = moneyAll;
        this.averageMoney = averageMoney;
        this.time = time;
        this.year = year;
        this.timeRange = timeRange;
        this.info = info;
        this.companyId = companyId;
        this.crtUid = crtUid;
        this.crtTime = crtTime;
        this.updUid = updUid;
        this.updTime = updTime;
    }
    
    @Id
    @GeneratedValue(generator = "financingStatisticGenerator")    
    @GenericGenerator(name = "financingStatisticGenerator", strategy = "uuid") 
    @Column(name = "STATISTIC_ID", unique = true, nullable = false, length = 128)
    public String getStatisticId()
    {
        return this.statisticId;
    }
    
    public void setStatisticId(String statisticId)
    {
        this.statisticId = statisticId;
    }
    
    @Column(name = "EMPLOYEE_ID", length = 128)
    public String getEmployeeId()
    {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId)
    {
        this.employeeId = employeeId;
    }
    
    @Column(name = "EMPLOYEE_NAME", length = 100)
    public String getEmployeeName()
    {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName)
    {
        this.employeeName = employeeName;
    }
    
    @Column(name = "CUSTOMER_NUMS", length = 2)
    public String getCustomerNums()
    {
        return this.customerNums;
    }
    
    public void setCustomerNums(String customerNums)
    {
        this.customerNums = customerNums;
    }
    
    @Column(name = "MONEY_ALL", length = 100)
    public String getMoneyAll()
    {
        return this.moneyAll;
    }
    
    public void setMoneyAll(String moneyAll)
    {
        this.moneyAll = moneyAll;
    }
    
    @Column(name = "AVERAGE_MONEY")
    public Integer getAverageMoney()
    {
        return this.averageMoney;
    }
    
    public void setAverageMoney(Integer averageMoney)
    {
        this.averageMoney = averageMoney;
    }
    
    @Column(name = "TIME", length = 4)
    public String getTime()
    {
        return this.time;
    }
    
    public void setTime(String time)
    {
        this.time = time;
    }
    
    @Column(name = "YEAR", length = 4)
    public String getYear()
    {
        return this.year;
    }
    
    public void setYear(String year)
    {
        this.year = year;
    }
    
    @Column(name = "TIME_RANGE", length = 100)
    public String getTimeRange()
    {
        return this.timeRange;
    }
    
    public void setTimeRange(String timeRange)
    {
        this.timeRange = timeRange;
    }
    
    @Column(name = "INFO", length = 555)
    public String getInfo()
    {
        return this.info;
    }
    
    public void setInfo(String info)
    {
        this.info = info;
    }
    
    @Column(name = "COMPANY_ID", length = 128)
    public String getCompanyId()
    {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId)
    {
        this.companyId = companyId;
    }
    
    @Column(name = "CRT_UID", length = 128)
    public String getCrtUid()
    {
        return this.crtUid;
    }
    
    public void setCrtUid(String crtUid)
    {
        this.crtUid = crtUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CRT_TIME", length = 19)
    public Date getCrtTime()
    {
        return this.crtTime;
    }
    
    public void setCrtTime(Date crtTime)
    {
        this.crtTime = crtTime;
    }
    
    @Column(name = "UPD_UID", length = 128)
    public String getUpdUid()
    {
        return this.updUid;
    }
    
    public void setUpdUid(String updUid)
    {
        this.updUid = updUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPD_TIME", length = 19)
    public Date getUpdTime()
    {
        return this.updTime;
    }
    
    public void setUpdTime(Date updTime)
    {
        this.updTime = updTime;
    }
    
}
