package com.deying.core.pojo;
// default package
// Generated 2016-6-26 13:56:20 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * TblFinancing generated by hbm2java
 */
@Entity
@Table(name = "tbl_financing",  uniqueConstraints = @UniqueConstraint(columnNames = {"FINANCING_ID",
    "FINANCING_NAME"}))
public class Financing implements java.io.Serializable
{
    
    private String financingId;
    
    
    private String financingName;
    
    private String financingDesc;
    
    private String type;
    
    private BigDecimal annualizedRate;
    
    private String months;
    
    private BigDecimal annualizedRateEnd;
    
    private String monthsEnd;
    
    private String startUp;
    
    private String companyId;
    
    private String crtUid;
    
    private Date crtTime;
    
    private String updUid;
    
    private Date updTime;
    
    public Financing()
    {
    }
    
    public Financing(String financingId, String financingTypeId, String financingName, String type,
        BigDecimal annualizedRate, String months, String startUp)
    {
        this.financingId = financingId;
        this.financingName = financingName;
        this.type = type;
        this.annualizedRate = annualizedRate;
        this.months = months;
        this.startUp = startUp;
    }
    
    public Financing(String financingId, String financingTypeId, String financingName, String financingDesc,
        String type, BigDecimal annualizedRate, String months,   BigDecimal annualizedRateEnd, String monthsEnd, String startUp, String companyId, String crtUid,
        Date crtTime, String updUid, Date updTime)
    {
        this.financingId = financingId;
        this.financingName = financingName;
        this.financingDesc = financingDesc;
        this.type = type;
        this.annualizedRate = annualizedRate;
        this.months = months;
        this.annualizedRateEnd = annualizedRateEnd;
        this.monthsEnd = monthsEnd;
        this.startUp = startUp;
        this.companyId = companyId;
        this.crtUid = crtUid;
        this.crtTime = crtTime;
        this.updUid = updUid;
        this.updTime = updTime;
    }
    
    @Id
    
    @Column(name = "FINANCING_ID", unique = true, nullable = false, length = 128)
    @GeneratedValue(generator = "financingGenerator")    
    @GenericGenerator(name = "financingGenerator", strategy = "uuid") 
    public String getFinancingId()
    {
        return this.financingId;
    }
    
    public void setFinancingId(String financingId)
    {
        this.financingId = financingId;
    }
    
    @Column(name = "FINANCING_NAME", nullable = false, length = 100)
    public String getFinancingName()
    {
        return this.financingName;
    }
    
    public void setFinancingName(String financingName)
    {
        this.financingName = financingName;
    }
    
    @Column(name = "FINANCING_DESC")
    public String getFinancingDesc()
    {
        return this.financingDesc;
    }
    
    public void setFinancingDesc(String financingDesc)
    {
        this.financingDesc = financingDesc;
    }
    
    @Column(name = "TYPE", nullable = false, length = 2)
    public String getType()
    {
        return this.type;
    }
    
    public void setType(String type)
    {
        this.type = type;
    }
    
    @Column(name = "ANNUALIZED_RATE", nullable = false, precision = 10, scale = 1)
    public BigDecimal getAnnualizedRate()
    {
        return this.annualizedRate;
    }
    
    public void setAnnualizedRate(BigDecimal annualizedRate)
    {
        this.annualizedRate = annualizedRate;
    }
    
    @Column(name = "ANNUALIZED_RATE_END", precision = 10, scale = 1)
    public BigDecimal getAnnualizedRateEnd()
    {
        return this.annualizedRateEnd;
    }
    
    public void setAnnualizedRateEnd(BigDecimal annualizedRateEnd)
    {
        this.annualizedRateEnd = annualizedRateEnd;
    }
    
    @Column(name = "MONTHS", nullable = false, length = 10)
    public String getMonths()
    {
        return this.months;
    }
    
    public void setMonths(String months)
    {
        this.months = months;
    }
    
    @Column(name = "MONTHS_END",  length = 10)
    public String getMonthsEnd()
    {
        return this.monthsEnd;
    }
    
    public void setMonthsEnd(String monthsEnd)
    {
        this.monthsEnd = monthsEnd;
    }
    
    @Column(name = "START_UP", nullable = false, length = 2)
    public String getStartUp()
    {
        return this.startUp;
    }
    
    public void setStartUp(String startUp)
    {
        this.startUp = startUp;
    }
    
    @Column(name = "COMPANY_ID", length = 128)
    public String getCompanyId()
    {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId)
    {
        this.companyId = companyId;
    }
    
    @Column(name = "CRT_UID", length = 128)
    public String getCrtUid()
    {
        return this.crtUid;
    }
    
    public void setCrtUid(String crtUid)
    {
        this.crtUid = crtUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CRT_TIME", length = 19)
    public Date getCrtTime()
    {
        return this.crtTime;
    }
    
    public void setCrtTime(Date crtTime)
    {
        this.crtTime = crtTime;
    }
    
    @Column(name = "UPD_UID", length = 128)
    public String getUpdUid()
    {
        return this.updUid;
    }
    
    public void setUpdUid(String updUid)
    {
        this.updUid = updUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPD_TIME", length = 19)
    public Date getUpdTime()
    {
        return this.updTime;
    }
    
    public void setUpdTime(Date updTime)
    {
        this.updTime = updTime;
    }
    
}
