package com.deying.core.pojo;
// default package
// Generated 2016-7-14 23:19:37 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TblFinancingRemind generated by hbm2java
 */
@Entity
@Table(name = "tbl_financing_remind", catalog = "yccf")
public class FinancingRemind implements java.io.Serializable
{
    
    private String financingRemindId;
    
    private String customerId;
    
    private String customerName;
    
    private Date startTime;
    
    private String type;
    
    private String dayType;
    
    private String info;
    
    private String employeeId;
    
    private String employeeName;
    
    private String companyId;
    
    private String status;
    
    private String crtUid;
    
    private Date crtTime;
    
    private String updUid;
    
    private Date updTime;
    
    public FinancingRemind()
    {
    }
    
    public FinancingRemind(String financingRemindId)
    {
        this.financingRemindId = financingRemindId;
    }
    
    public FinancingRemind(String financingRemindId, String customerId, String customerName, Date startTime,
        String type, String dayType, String info, String employeeId, String employeeName, String companyId,
        String status, String crtUid, Date crtTime, String updUid, Date updTime)
    {
        this.financingRemindId = financingRemindId;
        this.customerId = customerId;
        this.customerName = customerName;
        this.startTime = startTime;
        this.type = type;
        this.dayType = dayType;
        this.info = info;
        this.employeeId = employeeId;
        this.employeeName = employeeName;
        this.companyId = companyId;
        this.status = status;
        this.crtUid = crtUid;
        this.crtTime = crtTime;
        this.updUid = updUid;
        this.updTime = updTime;
    }
    
    @Id
    
    @Column(name = "FINANCING_REMIND_ID", unique = true, nullable = false, length = 128)
    @GeneratedValue(generator = "financingNnlGenerator")    
    @GenericGenerator(name = "financingNnlGenerator", strategy = "uuid") 
    public String getFinancingRemindId()
    {
        return this.financingRemindId;
    }
    
    public void setFinancingRemindId(String financingRemindId)
    {
        this.financingRemindId = financingRemindId;
    }
    
    @Column(name = "CUSTOMER_ID", length = 128)
    public String getCustomerId()
    {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId)
    {
        this.customerId = customerId;
    }
    
    @Column(name = "CUSTOMER_NAME")
    public String getCustomerName()
    {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName)
    {
        this.customerName = customerName;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_TIME", length = 19)
    public Date getStartTime()
    {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime)
    {
        this.startTime = startTime;
    }
    
    @Column(name = "TYPE", length = 2)
    public String getType()
    {
        return this.type;
    }
    
    public void setType(String type)
    {
        this.type = type;
    }
    
    @Column(name = "DAY_TYPE", length = 2)
    public String getDayType()
    {
        return this.dayType;
    }
    
    public void setDayType(String dayType)
    {
        this.dayType = dayType;
    }
    
    @Column(name = "INFO", length = 200)
    public String getInfo()
    {
        return this.info;
    }
    
    public void setInfo(String info)
    {
        this.info = info;
    }
    
    @Column(name = "EMPLOYEE_ID", length = 128)
    public String getEmployeeId()
    {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId)
    {
        this.employeeId = employeeId;
    }
    
    @Column(name = "EMPLOYEE_NAME")
    public String getEmployeeName()
    {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName)
    {
        this.employeeName = employeeName;
    }
    
    @Column(name = "COMPANY_ID", length = 128)
    public String getCompanyId()
    {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId)
    {
        this.companyId = companyId;
    }
    
    @Column(name = "STATUS", length = 2)
    public String getStatus()
    {
        return this.status;
    }
    
    public void setStatus(String status)
    {
        this.status = status;
    }
    
    @Column(name = "CRT_UID", length = 128)
    public String getCrtUid()
    {
        return this.crtUid;
    }
    
    public void setCrtUid(String crtUid)
    {
        this.crtUid = crtUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CRT_TIME", length = 19)
    public Date getCrtTime()
    {
        return this.crtTime;
    }
    
    public void setCrtTime(Date crtTime)
    {
        this.crtTime = crtTime;
    }
    
    @Column(name = "UPD_UID", length = 128)
    public String getUpdUid()
    {
        return this.updUid;
    }
    
    public void setUpdUid(String updUid)
    {
        this.updUid = updUid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPD_TIME", length = 19)
    public Date getUpdTime()
    {
        return this.updTime;
    }
    
    public void setUpdTime(Date updTime)
    {
        this.updTime = updTime;
    }
    
}
