package com.deying.core.pojo;

// Generated 2016-6-2 15:03:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * FinancingNnhDetail generated by hbm2java
 */
@Entity
@Table(name = "tbl_financing_nnh_detail",uniqueConstraints = @UniqueConstraint(columnNames = {
		"CUSTOMER_ID", "CUSTOMER_NAME" }))
public class FinancingNnhDetail implements java.io.Serializable {

	private String nnlDetailId;
	private String financingApplyId;
	private String customerId;
	private String customerName;
	private String type;
	private long money;
	private String permonthDay;
	private Long permonthReturnMoney;
	private String accountNumber;
	private String accountType;
	private String telephone;
	private Date financingStartTime;
	private Date financingEndTime;
	private String months;
	private String employeeId;
	private String employeeName;
	private String status;
	private String companyId;
	private String crtUid;
	private Date crtTime;
	private String updUid;
	private Date updTime;

	public FinancingNnhDetail() {
	}

	public FinancingNnhDetail(String nnlDetailId, String financingApplyId,
			String customerId, String customerName, String type, long money,
			String permonthDay, Date financingStartTime, Date financingEndTime,
			String months, String employeeId, String employeeName, String status) {
		this.nnlDetailId = nnlDetailId;
		this.financingApplyId = financingApplyId;
		this.customerId = customerId;
		this.customerName = customerName;
		this.type = type;
		this.money = money;
		this.permonthDay = permonthDay;
		this.financingStartTime = financingStartTime;
		this.financingEndTime = financingEndTime;
		this.months = months;
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.status = status;
	}

	public FinancingNnhDetail(String nnlDetailId, String financingApplyId,
			String customerId, String customerName, String type, long money,
			String permonthDay, Long permonthReturnMoney, String accountNumber,
			String accountType, String telephone, Date financingStartTime,
			Date financingEndTime, String months, String employeeId,
			String employeeName, String status, String companyId,
			String crtUid, Date crtTime, String updUid, Date updTime) {
		this.nnlDetailId = nnlDetailId;
		this.financingApplyId = financingApplyId;
		this.customerId = customerId;
		this.customerName = customerName;
		this.type = type;
		this.money = money;
		this.permonthDay = permonthDay;
		this.permonthReturnMoney = permonthReturnMoney;
		this.accountNumber = accountNumber;
		this.accountType = accountType;
		this.telephone = telephone;
		this.financingStartTime = financingStartTime;
		this.financingEndTime = financingEndTime;
		this.months = months;
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.status = status;
		this.companyId = companyId;
		this.crtUid = crtUid;
		this.crtTime = crtTime;
		this.updUid = updUid;
		this.updTime = updTime;
	}

	@Id
	@Column(name = "NNL_DETAIL_ID", unique = true, nullable = false, length = 128)
	@GeneratedValue(generator = "financingNnlGenerator")    
	@GenericGenerator(name = "financingNnlGenerator", strategy = "uuid") 
	public String getNnlDetailId() {
		return this.nnlDetailId;
	}

	public void setNnlDetailId(String nnlDetailId) {
		this.nnlDetailId = nnlDetailId;
	}

	@Column(name = "FINANCING_APPLY_ID", nullable = false, length = 128)
	public String getFinancingApplyId() {
		return this.financingApplyId;
	}

	public void setFinancingApplyId(String financingApplyId) {
		this.financingApplyId = financingApplyId;
	}

	@Column(name = "CUSTOMER_ID", nullable = false, length = 128)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CUSTOMER_NAME", nullable = false, length = 100)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "TYPE", nullable = false, length = 2)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "MONEY", nullable = false, precision = 10, scale = 0)
	public long getMoney() {
		return this.money;
	}

	public void setMoney(long money) {
		this.money = money;
	}

	@Column(name = "PERMONTH_DAY", nullable = false, length = 10)
	public String getPermonthDay() {
		return this.permonthDay;
	}

	public void setPermonthDay(String permonthDay) {
		this.permonthDay = permonthDay;
	}

	@Column(name = "PERMONTH_RETURN_MONEY", precision = 10, scale = 0)
	public Long getPermonthReturnMoney() {
		return this.permonthReturnMoney;
	}

	public void setPermonthReturnMoney(Long permonthReturnMoney) {
		this.permonthReturnMoney = permonthReturnMoney;
	}

	@Column(name = "ACCOUNT_NUMBER", length = 50)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "ACCOUNT_TYPE", length = 100)
	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "TELEPHONE", length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FINANCING_START_TIME", nullable = false, length = 0)
	public Date getFinancingStartTime() {
		return this.financingStartTime;
	}

	public void setFinancingStartTime(Date financingStartTime) {
		this.financingStartTime = financingStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FINANCING_END_TIME", nullable = false, length = 0)
	public Date getFinancingEndTime() {
		return this.financingEndTime;
	}

	public void setFinancingEndTime(Date financingEndTime) {
		this.financingEndTime = financingEndTime;
	}

	@Column(name = "MONTHS", nullable = false, length = 10)
	public String getMonths() {
		return this.months;
	}

	public void setMonths(String months) {
		this.months = months;
	}

	@Column(name = "EMPLOYEE_ID", nullable = false, length = 128)
	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "EMPLOYEE_NAME", nullable = false, length = 100)
	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	@Column(name = "STATUS", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COMPANY_ID", length = 128)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "CRT_UID", length = 128)
	public String getCrtUid() {
		return this.crtUid;
	}

	public void setCrtUid(String crtUid) {
		this.crtUid = crtUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRT_TIME", length = 0)
	public Date getCrtTime() {
		return this.crtTime;
	}

	public void setCrtTime(Date crtTime) {
		this.crtTime = crtTime;
	}

	@Column(name = "UPD_UID", length = 128)
	public String getUpdUid() {
		return this.updUid;
	}

	public void setUpdUid(String updUid) {
		this.updUid = updUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPD_TIME", length = 0)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

}
