package com.deying.core.pojo;

// Generated 2016-6-2 15:03:25 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * GoodsPurchase generated by hbm2java
 */
@Entity
@Table(name = "tbl_goods_purchase",uniqueConstraints = @UniqueConstraint(columnNames = {
		"GOODS_NAME", "NUMS" }))
public class GoodsPurchase implements java.io.Serializable {

	private String goodsPurchaseId;
	private String goodsId;
	private String goodsName;
	private BigDecimal price;
	private int nums;
	private BigDecimal totalPrice;
	private String reviewPerson;
	private Date reviewTime;
	private String status;
	private String companyId;
	private String crtUid;
	private Date crtTime;
	private String updUid;
	private Date updTime;

	public GoodsPurchase() {
	}

	public GoodsPurchase(String goodsPurchaseId, String goodsId,
			String goodsName, BigDecimal price, int nums,
			BigDecimal totalPrice, String status) {
		this.goodsPurchaseId = goodsPurchaseId;
		this.goodsId = goodsId;
		this.goodsName = goodsName;
		this.price = price;
		this.nums = nums;
		this.totalPrice = totalPrice;
		this.status = status;
	}

	public GoodsPurchase(String goodsPurchaseId, String goodsId,
			String goodsName, BigDecimal price, int nums,
			BigDecimal totalPrice, String reviewPerson, Date reviewTime,
			String status, String companyId, String crtUid, Date crtTime,
			String updUid, Date updTime) {
		this.goodsPurchaseId = goodsPurchaseId;
		this.goodsId = goodsId;
		this.goodsName = goodsName;
		this.price = price;
		this.nums = nums;
		this.totalPrice = totalPrice;
		this.reviewPerson = reviewPerson;
		this.reviewTime = reviewTime;
		this.status = status;
		this.companyId = companyId;
		this.crtUid = crtUid;
		this.crtTime = crtTime;
		this.updUid = updUid;
		this.updTime = updTime;
	}

	@Id
	@Column(name = "GOODS_PURCHASE_ID", unique = true, nullable = false, length = 128)
	@GeneratedValue(generator = "goodsPurchaseGenerator")    
	@GenericGenerator(name = "goodsPurchaseGenerator", strategy = "uuid") 
	public String getGoodsPurchaseId() {
		return this.goodsPurchaseId;
	}

	public void setGoodsPurchaseId(String goodsPurchaseId) {
		this.goodsPurchaseId = goodsPurchaseId;
	}

	@Column(name = "GOODS_ID", nullable = false, length = 128)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@Column(name = "GOODS_NAME", nullable = false, length = 100)
	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	@Column(name = "PRICE", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "NUMS", nullable = false)
	public int getNums() {
		return this.nums;
	}

	public void setNums(int nums) {
		this.nums = nums;
	}

	@Column(name = "TOTAL_PRICE", nullable = false, precision = 10)
	public BigDecimal getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "REVIEW_PERSON", length = 100)
	public String getReviewPerson() {
		return this.reviewPerson;
	}

	public void setReviewPerson(String reviewPerson) {
		this.reviewPerson = reviewPerson;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REVIEW_TIME", length = 0)
	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}

	@Column(name = "STATUS", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COMPANY_ID", length = 128)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "CRT_UID", length = 128)
	public String getCrtUid() {
		return this.crtUid;
	}

	public void setCrtUid(String crtUid) {
		this.crtUid = crtUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRT_TIME", length = 0)
	public Date getCrtTime() {
		return this.crtTime;
	}

	public void setCrtTime(Date crtTime) {
		this.crtTime = crtTime;
	}

	@Column(name = "UPD_UID", length = 128)
	public String getUpdUid() {
		return this.updUid;
	}

	public void setUpdUid(String updUid) {
		this.updUid = updUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPD_TIME", length = 0)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

}
