package com.deying.core.pojo;

// Generated 2016-6-2 15:03:25 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * GoodsStock generated by hbm2java
 */
@Entity
@Table(name = "tbl_goods_stock",uniqueConstraints = @UniqueConstraint(columnNames = {
		"GOODS_NAME", "NUMS_ALL" }))
public class GoodsStock implements java.io.Serializable {

	private String goodsId;
	private String goodsName;
	private BigDecimal price;
	private int numsAll;
	private int numsNow;
	private int numsWarning;
	private String status;
	private String companyId;
	private String crtUid;
	private Date crtTime;
	private String updUid;
	private Date updTime;

	public GoodsStock() {
	}

	public GoodsStock(String goodsId, String goodsName, BigDecimal price,
			int numsAll, int numsNow, int numsWarning, String status) {
		this.goodsId = goodsId;
		this.goodsName = goodsName;
		this.price = price;
		this.numsAll = numsAll;
		this.numsNow = numsNow;
		this.numsWarning = numsWarning;
		this.status = status;
	}

	public GoodsStock(String goodsId, String goodsName, BigDecimal price,
			int numsAll, int numsNow, int numsWarning, String status,
			String companyId, String crtUid, Date crtTime, String updUid,
			Date updTime) {
		this.goodsId = goodsId;
		this.goodsName = goodsName;
		this.price = price;
		this.numsAll = numsAll;
		this.numsNow = numsNow;
		this.numsWarning = numsWarning;
		this.status = status;
		this.companyId = companyId;
		this.crtUid = crtUid;
		this.crtTime = crtTime;
		this.updUid = updUid;
		this.updTime = updTime;
	}

	@Id
	@Column(name = "GOODS_ID", unique = true, nullable = false, length = 128)
	@GeneratedValue(generator = "goodsGenerator")    
	@GenericGenerator(name = "goodsGenerator", strategy = "uuid") 
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@Column(name = "GOODS_NAME", nullable = false, length = 100)
	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	@Column(name = "PRICE", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "NUMS_ALL", nullable = false)
	public int getNumsAll() {
		return this.numsAll;
	}

	public void setNumsAll(int numsAll) {
		this.numsAll = numsAll;
	}

	@Column(name = "NUMS_NOW", nullable = false)
	public int getNumsNow() {
		return this.numsNow;
	}

	public void setNumsNow(int numsNow) {
		this.numsNow = numsNow;
	}

	@Column(name = "NUMS_WARNING", nullable = false)
	public int getNumsWarning() {
		return this.numsWarning;
	}

	public void setNumsWarning(int numsWarning) {
		this.numsWarning = numsWarning;
	}

	@Column(name = "STATUS", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COMPANY_ID", length = 128)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "CRT_UID", length = 128)
	public String getCrtUid() {
		return this.crtUid;
	}

	public void setCrtUid(String crtUid) {
		this.crtUid = crtUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRT_TIME", length = 0)
	public Date getCrtTime() {
		return this.crtTime;
	}

	public void setCrtTime(Date crtTime) {
		this.crtTime = crtTime;
	}

	@Column(name = "UPD_UID", length = 128)
	public String getUpdUid() {
		return this.updUid;
	}

	public void setUpdUid(String updUid) {
		this.updUid = updUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPD_TIME", length = 0)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

}
