package com.deying.core.pojo;

// Generated 2016-6-2 15:03:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MMessage generated by hbm2java
 */
@Entity
@Table(name = "m_message")
public class MMessage implements java.io.Serializable {

	private Long id;
	private int state;
	private String title;
	private String content;
	private String detailUrl;
	private int msgModule;
	private int msgType;
	private String entityId;
	private int accepterType;
	private String accepterId;
	private String accepter;
	private int addressorType;
	private String addressorId;
	private String addressor;
	private String realAddressorId;
	private String realAddressor;
	private String remark;
	private Date createTime;
	private Date modifyTime;

	public MMessage() {
	}

	public MMessage(int state, String content, int msgModule, int msgType,
			int accepterType, String accepterId, String accepter,
			int addressorType, String addressorId, String addressor,
			Date createTime) {
		this.state = state;
		this.content = content;
		this.msgModule = msgModule;
		this.msgType = msgType;
		this.accepterType = accepterType;
		this.accepterId = accepterId;
		this.accepter = accepter;
		this.addressorType = addressorType;
		this.addressorId = addressorId;
		this.addressor = addressor;
		this.createTime = createTime;
	}

	public MMessage(int state, String title, String content, String detailUrl,
			int msgModule, int msgType, String entityId, int accepterType,
			String accepterId, String accepter, int addressorType,
			String addressorId, String addressor, String realAddressorId,
			String realAddressor, String remark, Date createTime,
			Date modifyTime) {
		this.state = state;
		this.title = title;
		this.content = content;
		this.detailUrl = detailUrl;
		this.msgModule = msgModule;
		this.msgType = msgType;
		this.entityId = entityId;
		this.accepterType = accepterType;
		this.accepterId = accepterId;
		this.accepter = accepter;
		this.addressorType = addressorType;
		this.addressorId = addressorId;
		this.addressor = addressor;
		this.realAddressorId = realAddressorId;
		this.realAddressor = realAddressor;
		this.remark = remark;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "title", length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", nullable = false, length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "detailUrl")
	public String getDetailUrl() {
		return this.detailUrl;
	}

	public void setDetailUrl(String detailUrl) {
		this.detailUrl = detailUrl;
	}

	@Column(name = "msgModule", nullable = false)
	public int getMsgModule() {
		return this.msgModule;
	}

	public void setMsgModule(int msgModule) {
		this.msgModule = msgModule;
	}

	@Column(name = "msgType", nullable = false)
	public int getMsgType() {
		return this.msgType;
	}

	public void setMsgType(int msgType) {
		this.msgType = msgType;
	}

	@Column(name = "entityId", length = 40)
	public String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}

	@Column(name = "accepterType", nullable = false)
	public int getAccepterType() {
		return this.accepterType;
	}

	public void setAccepterType(int accepterType) {
		this.accepterType = accepterType;
	}

	@Column(name = "accepterId", nullable = false, length = 128)
	public String getAccepterId() {
		return this.accepterId;
	}

	public void setAccepterId(String accepterId) {
		this.accepterId = accepterId;
	}

	@Column(name = "accepter", nullable = false, length = 128)
	public String getAccepter() {
		return this.accepter;
	}

	public void setAccepter(String accepter) {
		this.accepter = accepter;
	}

	@Column(name = "addressorType", nullable = false)
	public int getAddressorType() {
		return this.addressorType;
	}

	public void setAddressorType(int addressorType) {
		this.addressorType = addressorType;
	}

	@Column(name = "addressorId", nullable = false, length = 128)
	public String getAddressorId() {
		return this.addressorId;
	}

	public void setAddressorId(String addressorId) {
		this.addressorId = addressorId;
	}

	@Column(name = "addressor", nullable = false, length = 128)
	public String getAddressor() {
		return this.addressor;
	}

	public void setAddressor(String addressor) {
		this.addressor = addressor;
	}

	@Column(name = "realAddressorId", length = 128)
	public String getRealAddressorId() {
		return this.realAddressorId;
	}

	public void setRealAddressorId(String realAddressorId) {
		this.realAddressorId = realAddressorId;
	}

	@Column(name = "realAddressor", length = 128)
	public String getRealAddressor() {
		return this.realAddressor;
	}

	public void setRealAddressor(String realAddressor) {
		this.realAddressor = realAddressor;
	}

	@Column(name = "remark", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 0)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifyTime", length = 0)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
