package com.deying.core.pojo;
 
//default package
//Generated 2016-7-24 2:53:14 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
* TblTeam generated by hbm2java
*/
@Entity
@Table(name = "com_user_team")
public class UserTeam implements java.io.Serializable
{
 
 private String teamId;
 
 private String userId;
 
 private String userName;

 private String companyId;
 
 private String teamUserId;
 
 private String teamUserName;
 
 private String status;

 private String crtUid;
 
 private Date crtTime;
 
 private String updUid;
 
 private Date updTime;
 
 public UserTeam()
 {
 }
 
 public UserTeam(String teamId, String userId, String companyId, String userName, String teamUserId,
     String teamUserName, String status,  String crtUid, Date crtTime, String updUid, Date updTime)
 {
     this.teamId = teamId;
     this.userId = userId;
     this.companyId = companyId;
     this.userName = userName;
     this.teamUserId = teamUserId;
     this.teamUserName = teamUserName;
     this.status = status;
     this.crtUid = crtUid;
     this.crtTime = crtTime;
     this.updUid = updUid;
     this.updTime = updTime;
 }
 
 @Id
 @GeneratedValue(generator = "teamCollectionGenerator")    
 @GenericGenerator(name = "teamCollectionGenerator", strategy = "uuid") 
 @Column(name = "TEAM_ID", unique = true, nullable = false, length = 128)
 public String getTeamId()
 {
     return this.teamId;
 }
 
 public void setTeamId(String teamId)
 {
     this.teamId = teamId;
 }
 
 @Column(name = "USER_ID", length = 128)
 public String getUserId()
 {
     return this.userId;
 }
 
 public void setUserId(String userId)
 {
     this.userId = userId;
 }
 
 @Column(name = "COMPANY_ID", nullable = false, length = 128)
 public String getCompanyId()
 {
     return this.companyId;
 }
 
 public void setCompanyId(String companyId)
 {
     this.companyId = companyId;
 }
 
 @Column(name = "USER_NAME", length = 100)
 public String getUserName()
 {
     return this.userName;
 }
 
 public void setUserName(String userName)
 {
     this.userName = userName;
 }

 @Column(name = "TEAM_USER_NAME", length = 100)
 public String getTeamUserName()
 {
     return this.teamUserName;
 }
 
 public void setTeamUserName(String teamUserName)
 {
     this.teamUserName = teamUserName;
 }
 
 @Column(name = "TEAM_USER_ID", length = 100)
 public String getTeamUserId()
 {
     return this.teamUserId;
 }
 
 public void setTeamUserId(String teamUserId)
 {
     this.teamUserId = teamUserId;
 }
 
 
 @Column(name = "CRT_UID", length = 128)
 public String getCrtUid()
 {
     return this.crtUid;
 }
 
 public void setCrtUid(String crtUid)
 {
     this.crtUid = crtUid;
 }
 
 @Temporal(TemporalType.TIMESTAMP)
 @Column(name = "CRT_TIME", length = 19)
 public Date getCrtTime()
 {
     return this.crtTime;
 }
 
 public void setCrtTime(Date crtTime)
 {
     this.crtTime = crtTime;
 }
 
 @Column(name = "UPD_UID", length = 128)
 public String getUpdUid()
 {
     return this.updUid;
 }
 
 public void setUpdUid(String updUid)
 {
     this.updUid = updUid;
 }
 
 @Temporal(TemporalType.TIMESTAMP)
 @Column(name = "UPD_TIME", length = 19)
 public Date getUpdTime()
 {
     return this.updTime;
 }
 
 public void setUpdTime(Date updTime)
 {
     this.updTime = updTime;
 }
}
